services:
  - type: web
    name: mern-calculator
    env: node
    buildCommand: npm install && cd server && npm install && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
